version: '3'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
  nats:
    image: "nats"
    ports:
     - "4222:4222"
     - "6222:6222"
     - "8222:8222"
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  elasticsearch:
    image: "elasticsearch:5-alpine"
    ports:
     - "9200:9200"
     - "9300:9300"
  redis:
    image: "redis"
    ports:
     - "6379:6379"
  kafka:
    image: "landoop/fast-data-dev"
    environment:
    - ADV_HOST=127.0.0.1
    - SAMPLEDATA=0
    - RUNTESTS=0
    - FORWARDLOGS=0
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"

#  nats:
#    image: nats-streaming
#    hostname: nats
#    command: ["--store", "file", "--dir", "./data", "--max_msgs", "0", "--max_bytes", "0"]
#    ports:
#      - "4222:4222"
#      - "8222:8222"
#    restart: on-failure

volumes:
  data:
    driver: local
  db:
    driver: local
