version: '3'
services:
  nats:
    image: nats-streaming
    hostname: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: on-failure
  gateway:
    build: gateway
    environment:
      - TRANSPORT_URL=nats://nats:4222
    ports:
      - "3000:3000"
  db:
    build: db
    environment:
      - TRANSPORT_URL=nats://nats:4222
  search:
    build: search
    environment:
      - TRANSPORT_URL=nats://nats:4222
  entity:
    build: domain-entity
    environment:
      - TRANSPORT_URL=nats://nats:4222
