version: '3'
services:
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
  elasticsearch:
    image: "elasticsearch:5-alpine"
    ports:
     - "9200:9200"
     - "9300:9300"
  redis:
    image: "redis"
    ports:
     - "6379:6379"
  nats:
    image: "nats"
    ports:
     - "4222:4222"
     - "6222:6222"
     - "8222:8222"
  kafka:
    image: "landoop/fast-data-dev"
    environment:
    - ADV_HOST=127.0.0.1
    - SAMPLEDATA=0
    - RUNTESTS=0
    - FORWARDLOGS=0
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"

  mail:
    build: mail
    env_file: docker-compose.env
    depends_on:
      - maildev
    
  gateway:
    build: gateway
    env_file: docker-compose.env
    ports:
      - "3000:3000"

  event-store:
    build: event-store
    env_file: docker-compose.env
    depends_on: 
     - kafka

  search:
    build: search
    env_file: docker-compose.env
    depends_on: 
     - elasticsearch

  entity:
    build: entity
    env_file: docker-compose.env

  user:
    build: user
    env_file: docker-compose.env
    depends_on:
      - mail

  metrics:
    build: metrics
    env_file: docker-compose.env

volumes:
  data:
    driver: local
  db:
    driver: local