version: '3'
services:
  nats:
    image: nats-streaming
    hostname: nats
    command: ["--store", "file", "--dir", "./data", "--max_msgs", "0", "--max_bytes", "0"]
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: on-failure
