version: '3'
services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    restart: on-failure
#  kafka:
#    image: spotify/kafka
#    hostname: kafka
#    extra_hosts:
#      - "moby:127.0.0.1"
#    environment:
#      ADVERTISED_HOST: 192.168.1.41
#      TOPICS: items,search
#      ADVERTISED_PORT: 9092
#    ports:
#      - "9092:9092"
#      - "2181:2181"
#    restart: on-failure
